### ISSUE TITLE
[BUG] sendReadReceipt not working in version 4.3 and 4.4

### ISSUE THREAD

**Issue by DGXeon** [adiwajshing/Baileys#2112]
TypeError: XeonBotInc.sendReadReceipt is not a function
    at XeonBotInc (/storage/emulated/0/CheemsBot-MD4/XeonCheems4.js:10659:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by SheIITear** [comment]
Not a bug, read the documentation before making issues - [https://github.com/adiwajshing/Baileys#reading-messages](here).

**Comment by DGXeon** [comment]
> 

😂😂 u here skid

**Comment by DGXeon** [comment]
> changed to sock.readMessages([key])

thanks it worked

**Comment by SamPandey001** [comment]
> > 
> 
> 😂😂 u here skid

Atleast close this issue.
This isn't even bug,you just didn't read documentation
